# -*- coding: utf-8 -*-
"""hw5.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xXSf6D_0O6y_YN5vQA07XZ2LCH4m_6GP
"""

def read_single_digit(a):
  if a==1:
    print("일",end=' ')
  elif a==2:
    print("이",end=' ')
  elif a==3:
    print("삼",end=' ')
  elif a==4:
    print("사",end=' ')
  elif a==5:
    print("오",end=' ')
  elif a==6:
    print("육",end=' ')
  elif a==7:
    print("칠",end=' ')
  elif a==8:
    print("팔",end=' ')
  elif a==9:
    print("구",end=' ')
  elif a==0:
    print("공",end=' ')
def read_number(b):
  f=b//100
  b=b%100
  read_single_digit(f)
  s=b//10
  b=b%10
  read_single_digit(s)
  read_single_digit(b)

y=int(input("세 자리 정수 입력: "))
read_number(y)

b=128
r=b/100
print(r)