# -*- coding: utf-8 -*-
"""hw6

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xXSf6D_0O6y_YN5vQA07XZ2LCH4m_6GP
"""

for a in range(1,10):
  for b in range(2,6):
    print(f'{b} x {a} = {a*b:2d}',end='     ')
  print()
print()
for a in range(1,10):
  for b in range(6,10):
    print(f'{b} x {a} = {a*b:2d}',end='     ')
  print()