# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KKrLH-UXwjeS50XLwdmwY1_ZXJrmEkeB
"""

a=scanf("김건을 입력하시오")
print(a)